/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package computerstoreapplication;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class AdminMenuFrame extends javax.swing.JFrame {

    private Connection connection;
    /**
     * Creates new form AdminMenuFrame
     */
    public AdminMenuFrame() {
        initComponents();
        
        try {
            String path = "/resources/images/employee.png";
            BufferedImage img = ImageIO.read(getClass().getResource(path));
            Image icon = img.getScaledInstance(
                employeeLabel.getWidth(),
                employeeLabel.getHeight(),
                Image.SCALE_SMOOTH
            );
            employeeLabel.setIcon(new ImageIcon(icon));
        } catch (IOException ex) {
            Logger.getLogger(AdminMenuFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            connection = DBConnection.getConnection();
            
            String query = "SELECT * FROM product";
            PreparedStatement statement = connection.prepareStatement(query);
            ResultSet resultSet = statement.executeQuery();
            GuiUtils.resultSetToTableModel(resultSet, jTable);
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AdminMenuFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jTable.getSelectionModel().addListSelectionListener((ListSelectionEvent lse) -> {
            jTableValueChanged(lse);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        productTabTitle = new javax.swing.JLabel();
        modelTextField = new javax.swing.JTextField();
        makerTextField = new javax.swing.JTextField();
        typeTextField = new javax.swing.JTextField();
        priceTextField = new javax.swing.JTextField();
        modelLabel = new javax.swing.JLabel();
        makeLabel = new javax.swing.JLabel();
        productTypeLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        addProductButton = new javax.swing.JButton();
        updateProductButton = new javax.swing.JButton();
        removeProductButton = new javax.swing.JButton();
        productAmountTextField = new javax.swing.JTextField();
        productAmountLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        usernameTF = new javax.swing.JTextField();
        roleTF = new javax.swing.JTextField();
        workerLabel = new javax.swing.JLabel();
        roleLabel = new javax.swing.JLabel();
        idTF = new javax.swing.JTextField();
        idLabel = new javax.swing.JLabel();
        removeEmployeeButton = new javax.swing.JButton();
        updateEmployeeButton = new javax.swing.JButton();
        addEmployeeButton = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();
        passwordLabel = new javax.swing.JLabel();
        employeeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(51, 0, 153));

        jPanel2.setBackground(new java.awt.Color(51, 0, 153));

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable);

        productTabTitle.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        productTabTitle.setForeground(new java.awt.Color(255, 255, 255));
        productTabTitle.setText("Управление продуктами");

        modelTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                modelTextFieldFocusLost(evt);
            }
        });

        modelLabel.setForeground(new java.awt.Color(255, 255, 255));
        modelLabel.setText("Модель:");

        makeLabel.setForeground(new java.awt.Color(255, 255, 255));
        makeLabel.setText("Производитель:");

        productTypeLabel.setForeground(new java.awt.Color(255, 255, 255));
        productTypeLabel.setText("Тип:");

        priceLabel.setForeground(new java.awt.Color(255, 255, 255));
        priceLabel.setText("Цена:");

        addProductButton.setBackground(new java.awt.Color(0, 102, 0));
        addProductButton.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        addProductButton.setForeground(new java.awt.Color(255, 255, 255));
        addProductButton.setText("Добавить");
        addProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductButtonActionPerformed(evt);
            }
        });

        updateProductButton.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        updateProductButton.setText("Изменить");
        updateProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateProductButtonActionPerformed(evt);
            }
        });

        removeProductButton.setBackground(new java.awt.Color(102, 0, 0));
        removeProductButton.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        removeProductButton.setForeground(new java.awt.Color(255, 255, 255));
        removeProductButton.setText("Удалить");
        removeProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeProductButtonActionPerformed(evt);
            }
        });

        productAmountLabel.setForeground(new java.awt.Color(255, 255, 255));
        productAmountLabel.setText("Количество:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(productTabTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(updateProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                .addComponent(removeProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(addProductButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(modelLabel)
                                    .addComponent(makeLabel)
                                    .addComponent(productTypeLabel)
                                    .addComponent(priceLabel)
                                    .addComponent(productAmountLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(productAmountTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(priceTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(typeTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(makerTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(modelTextField))))
                        .addGap(38, 38, 38)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(productTabTitle)
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modelLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(makerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(makeLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(typeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productTypeLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(productAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productAmountLabel))
                        .addGap(18, 18, 18)
                        .addComponent(addProductButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(removeProductButton)
                            .addComponent(updateProductButton))
                        .addContainerGap(44, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Товары", jPanel2);

        jPanel1.setBackground(new java.awt.Color(51, 0, 153));

        usernameTF.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        roleTF.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        workerLabel.setForeground(new java.awt.Color(255, 255, 255));
        workerLabel.setText("Имя пользователя:");

        roleLabel.setForeground(new java.awt.Color(255, 255, 255));
        roleLabel.setText("Роль:");

        idTF.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        idTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTFActionPerformed(evt);
            }
        });

        idLabel.setForeground(new java.awt.Color(255, 255, 255));
        idLabel.setText("ID сотрудника:");

        removeEmployeeButton.setBackground(new java.awt.Color(102, 0, 0));
        removeEmployeeButton.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        removeEmployeeButton.setForeground(new java.awt.Color(255, 255, 255));
        removeEmployeeButton.setText("Удалить");
        removeEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeEmployeeButtonActionPerformed(evt);
            }
        });

        updateEmployeeButton.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        updateEmployeeButton.setText("Изменить");
        updateEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateEmployeeButtonActionPerformed(evt);
            }
        });

        addEmployeeButton.setBackground(new java.awt.Color(0, 102, 0));
        addEmployeeButton.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        addEmployeeButton.setForeground(new java.awt.Color(255, 255, 255));
        addEmployeeButton.setText("Добавить");
        addEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeButtonActionPerformed(evt);
            }
        });

        passwordField.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        passwordLabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel.setText("Пароль:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(removeEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updateEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(employeeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(workerLabel)
                            .addComponent(idLabel)
                            .addComponent(roleLabel)
                            .addComponent(passwordLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(passwordField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                .addComponent(idTF, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(usernameTF, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(roleTF, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addGap(115, 115, 115))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(workerLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(roleTF, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roleLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordLabel)
                            .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(addEmployeeButton))
                    .addComponent(employeeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateEmployeeButton)
                    .addComponent(removeEmployeeButton))
                .addGap(22, 22, 22))
        );

        jTabbedPane1.addTab("Сотрудники", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Сотрудники");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearEmployeeTabFields() {
        idTF.setText(null);
        clearEmployeeTabFieldsExceptId();
    }
    
    private void clearEmployeeTabFieldsExceptId() {
        usernameTF.setText(null);
        passwordField.setText(null);
        roleTF.setText(null);
    }
    
    private void jTableValueChanged(ListSelectionEvent lse) {
        DefaultTableModel defModel = (DefaultTableModel) jTable.getModel();
        int rowIdx = jTable.getSelectedRow();
        
        if (rowIdx < 0) {
            return;
        }
        
        String model = (String) defModel.getValueAt(rowIdx, 0);
        String maker = (String) defModel.getValueAt(rowIdx, 1);
        String type = (String) defModel.getValueAt(rowIdx, 2);
        Integer price = (Integer) defModel.getValueAt(rowIdx, 3);
        Integer amount = (Integer) defModel.getValueAt(rowIdx, 4);
        
        modelTextField.setText(model);
        makerTextField.setText(maker);
        typeTextField.setText(type);
        priceTextField.setText(price.toString());
        productAmountTextField.setText(amount.toString());
        
        addProductButton.setVisible(false);
        updateProductButton.setVisible(true);
        removeProductButton.setVisible(true);
    }
    
    private void idTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTFActionPerformed
        String query = "SELECT * FROM users WHERE id=?";
        try {
            PreparedStatement statement = connection.prepareStatement(query);
            statement.setInt(1, Integer.parseInt(idTF.getText()));
            ResultSet res = statement.executeQuery();
            
            if (res.next()) {
                usernameTF.setText(res.getString("username"));
                roleTF.setText(res.getString("role"));
                passwordField.setText(res.getString("password"));
                addEmployeeButton.setVisible(false);
                removeEmployeeButton.setVisible(true);
                updateEmployeeButton.setVisible(true);
            } else {
                clearEmployeeTabFieldsExceptId();
                
                addEmployeeButton.setVisible(true);
                removeEmployeeButton.setVisible(false);
                updateEmployeeButton.setVisible(false);
            }
        } catch (SQLException ex) { 
            Logger.getLogger(AdminMenuFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_idTFActionPerformed

    private void addEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeButtonActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(idTF.getText());
        String username = usernameTF.getText();
        String password = String.valueOf(passwordField.getPassword());
        int role = Integer.parseInt(roleTF.getText());

        
        try {
            DbUtils.insertUser(id, username, password, role, connection);
            clearEmployeeTabFields();
            
            JOptionPane.showMessageDialog(this, "Сотрудник успешно добавлен!");
            
        } catch (NoSuchAlgorithmException | SQLException ex) {
            Logger.getLogger(AdminMenuFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addEmployeeButtonActionPerformed

    private void updateEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateEmployeeButtonActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(idTF.getText());
        String username = usernameTF.getText();
        String password = String.valueOf(passwordField.getPassword());
        int role = Integer.parseInt(roleTF.getText());

        
        try {
            DbUtils.updateUser(id, username, password, role, connection);
            
            clearEmployeeTabFields();
            
            JOptionPane.showMessageDialog(this, "Изменение произошло успешно!");
            
        } catch (NoSuchAlgorithmException | SQLException ex) {
            Logger.getLogger(AdminMenuFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateEmployeeButtonActionPerformed

    private void removeEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeEmployeeButtonActionPerformed
        // TODO add your handling code here:
        try {
            DbUtils.deleteUserById(Integer.parseInt(idTF.getText()), connection);
            
            clearEmployeeTabFields();
            
            JOptionPane.showMessageDialog(this, "Запись успешно удалена!");
        } catch (SQLException ex) {
            Logger.getLogger(AdminMenuFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_removeEmployeeButtonActionPerformed

    private void addProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductButtonActionPerformed
        // TODO add your handling code here:
        String model = modelTextField.getText();
        String maker = makerTextField.getText();
        String type = typeTextField.getText();
        int price = Integer.parseInt(priceTextField.getText());
        int amount = Integer.parseInt(productAmountTextField.getText());
        
        DefaultTableModel defModel = (DefaultTableModel) jTable.getModel();
        defModel.addRow(new Object[] {model, maker, type, price, amount});
        
        try {
            DbUtils.insertProduct(model, maker, type, price, amount, connection);
        } catch (SQLException ex) {
            Logger.getLogger(AdminMenuFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        JOptionPane.showMessageDialog(this, "Продукт успешно добавлен!");
    }//GEN-LAST:event_addProductButtonActionPerformed

    private void removeProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeProductButtonActionPerformed
        // TODO add your handling code here:
        int rowIdx = jTable.getSelectedRow();        
        DefaultTableModel defModel = (DefaultTableModel) jTable.getModel();
        
        String model = (String) defModel.getValueAt(rowIdx, 0);

        defModel.removeRow(rowIdx);
        try {
            DbUtils.deleteProduct(model, connection);
        } catch (SQLException ex) {
            Logger.getLogger(AdminMenuFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        JOptionPane.showMessageDialog(this, "Запись успешно удалена!");
    }//GEN-LAST:event_removeProductButtonActionPerformed

    private void updateProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProductButtonActionPerformed
        // TODO add your handling code here:
        String model = modelTextField.getText();
        String maker = makerTextField.getText();
        String type = typeTextField.getText();
        int price = Integer.parseInt(priceTextField.getText());
        int amount = Integer.parseInt(productAmountTextField.getText());
        
        int row = jTable.getSelectedRow();
        DefaultTableModel tableModel = (DefaultTableModel) jTable.getModel();
        
        tableModel.setValueAt(model, row, 0);
        tableModel.setValueAt(maker, row, 1);
        tableModel.setValueAt(type, row, 2);
        tableModel.setValueAt(price, row, 3);
        tableModel.setValueAt(amount, row, 4);

        try {
            DbUtils.updateProduct(model, maker, type, price, amount, connection);
        } catch (SQLException ex) {
            Logger.getLogger(AdminMenuFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateProductButtonActionPerformed

    private void modelTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_modelTextFieldFocusLost
        // TODO add your handling code here:
        int row = jTable.getSelectedRow();
        DefaultTableModel tableModel = (DefaultTableModel) jTable.getModel();
        String productModel = (String) tableModel.getValueAt(row, 0);
        
        if (!productModel.equals(modelTextField.getText())) {
            addProductButton.setVisible(true);
            updateProductButton.setVisible(false);
            removeProductButton.setVisible(false);
        }
    }//GEN-LAST:event_modelTextFieldFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AdminMenuFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEmployeeButton;
    private javax.swing.JButton addProductButton;
    private javax.swing.JLabel employeeLabel;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTF;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JLabel makeLabel;
    private javax.swing.JTextField makerTextField;
    private javax.swing.JLabel modelLabel;
    private javax.swing.JTextField modelTextField;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JLabel productAmountLabel;
    private javax.swing.JTextField productAmountTextField;
    private javax.swing.JLabel productTabTitle;
    private javax.swing.JLabel productTypeLabel;
    private javax.swing.JButton removeEmployeeButton;
    private javax.swing.JButton removeProductButton;
    private javax.swing.JLabel roleLabel;
    private javax.swing.JTextField roleTF;
    private javax.swing.JTextField typeTextField;
    private javax.swing.JButton updateEmployeeButton;
    private javax.swing.JButton updateProductButton;
    private javax.swing.JTextField usernameTF;
    private javax.swing.JLabel workerLabel;
    // End of variables declaration//GEN-END:variables
}
